// <auto-generated />
using System;
using ChecklistMaster.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChecklistMaster.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260531174755_AddMilestoneMaster")]
    partial class AddMilestoneMaster
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChecklistMaster.Server.Models.CalendarEvent", b =>
                {
                    b.Property<string>("Uid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Flag1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Flag2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsGlobal")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsRecurring")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Uid");

                    b.ToTable("CalendarEvents");
                });

            modelBuilder.Entity("ChecklistMaster.Server.Models.ChecklistMasterEntity", b =>
                {
                    b.Property<string>("Uid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Area")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CheckPointS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CheckpointDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChkId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Flag1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Flag2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Flag3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Images")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mandatory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Material")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Owner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefDocument")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Station")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Uid");

                    b.ToTable("checklist_Master");
                });

            modelBuilder.Entity("ChecklistMaster.Server.Models.ChecklistMilestone", b =>
                {
                    b.Property<string>("Uid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CheckPointS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CheckpointDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChkId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Flag1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Flag2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Flag3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Milestone")
                        .HasColumnType("datetime2");

                    b.Property<string>("Milestoneid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NoofDays")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Uid");

                    b.ToTable("Checklists_Milestones");
                });

            modelBuilder.Entity("ChecklistMaster.Server.Models.ComponentMetadata", b =>
                {
                    b.Property<int>("Ouid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Ouid"));

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Activity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComponentCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComponentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Label")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Language")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Parameter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParameterCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Ouid");

                    b.ToTable("ComponentMetadata");
                });

            modelBuilder.Entity("ChecklistMaster.Server.Models.DmrsChecklist", b =>
                {
                    b.Property<string>("Uid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ChangeManagement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Check_Point")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Flag1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Flag2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Flag3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Issue_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MIMS_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MRS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Owner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source_Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SyncData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Uid");

                    b.ToTable("dmrs_Checklist");
                });

            modelBuilder.Entity("ChecklistMaster.Server.Models.IssueListChecklist", b =>
                {
                    b.Property<string>("Uid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Checklist_Desc")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("checklist_Desc");

                    b.Property<string>("Checlist_id")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("checlist_id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Issue_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PartNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks_LH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks_RH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Uid");

                    b.ToTable("Issue_list_checklist");
                });

            modelBuilder.Entity("ChecklistMaster.Server.Models.IssueListDocinfo", b =>
                {
                    b.Property<string>("Uid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Created_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Closed")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Opened")
                        .HasColumnType("datetime2");

                    b.Property<string>("Derogation_sht_num")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Flag1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Flag2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Flag3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Initiator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Issue_description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Issue_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Issue_title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LA_Num_LH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LA_Num_RH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Material")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modified_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Modified_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Owner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PA_Num_LH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PA_Num_RH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PDEF_Number_LH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PDEF_Number_RH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Req_Completion_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Uid");

                    b.ToTable("Issue_List_Docinfo");
                });

            modelBuilder.Entity("ChecklistMaster.Server.Models.IssueListHistory", b =>
                {
                    b.Property<string>("Uid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Flag1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Flag2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Flag3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Issue_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modified_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Modified_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("PartNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Uid");

                    b.ToTable("Issue_list_history");
                });

            modelBuilder.Entity("ChecklistMaster.Server.Models.IssueListPartinfo", b =>
                {
                    b.Property<string>("Uid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Comments_on_picture_LH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comments_on_picture_RH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Created_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Flag1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Flag2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Flag3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Issue_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Maturity_State_LH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Maturity_State_RH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modified_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Modified_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("PartNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Part_Revision_LH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Part_Revision_RH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Picture_lh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Picture_rh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Proposals")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Solutions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Uid");

                    b.ToTable("Issue_List_Partinfo");
                });

            modelBuilder.Entity("ChecklistMaster.Server.Models.MilestoneMaster", b =>
                {
                    b.Property<string>("Uid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Flag1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Flag2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Flag3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MilestoneName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MilestoneOrder")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NoOfDays")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Uid");

                    b.ToTable("Milestone_Master");
                });

            modelBuilder.Entity("ChecklistMaster.Server.Models.PartMilestone", b =>
                {
                    b.Property<string>("Uid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Flag1");

                    b.Property<string>("IssueNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MilestoneName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MilestoneOrder")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Owner")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Flag2");

                    b.Property<DateTime?>("PlannedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProjectUid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Uid");

                    b.ToTable("Part_Milestones");
                });

            modelBuilder.Entity("ChecklistMaster.Server.Models.Project", b =>
                {
                    b.Property<string>("Uid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Area")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Assy_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Created_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Flag1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Flag2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Flag3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modified_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Modified_date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("No_of_issues")
                        .HasColumnType("int");

                    b.Property<string>("PartName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Plant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Plant_year")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Program")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Project");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Uid");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("ChecklistMaster.Server.Models.ProjectIssueLink", b =>
                {
                    b.Property<string>("Uid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Area")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Created_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Flag1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Flag2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Flag3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Issue_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modified_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Modified_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("PartNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Part_Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Part_Description");

                    b.Property<string>("Part_number_LH")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Part_number_LH");

                    b.Property<string>("Part_number_RH")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Part_number_RH");

                    b.Property<string>("Plant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Plant_year")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Program")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Project")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Uid");

                    b.ToTable("Project_issue_link");
                });

            modelBuilder.Entity("ChecklistMaster.Server.Models.ProjectMilestone", b =>
                {
                    b.Property<string>("Uid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("AvpCompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Flag1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Flag2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Flag3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MilestoneName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MilestoneOrder")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PlannedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProjectUid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("WgdeCompletedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Uid");

                    b.ToTable("Project_Milestones");
                });

            modelBuilder.Entity("ChecklistMaster.Server.Models.User", b =>
                {
                    b.Property<string>("UId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Flag1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Flag2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Flag3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Lastlogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
